Add the POSIX semaphore feature from LMDB
meilisearch/heed pull request #140
Opened 2022-12-24 16:32 UTC by GregoryConrad

Before looking at this PR, please see https://github.com/meilisearch/lmdb-rs/pull/13. It is required before this PR can be merged.

This PR adds LMDB's POSIX semaphore feature to heed. This change allows iOS and macOS builds to be compliant with Apple's App Sandbox (necessary for distribution in the App Store), in addition to possible speed improvements brought upon by the POSIX semaphores.

You could investigate using POSIX semaphores within milli/meilisearch as well for the possible speed improvements they bring, but that is outside the scope of this PR.

2022-12-24 20:15 UTC, GregoryConrad commented
Also not sure whether this PR should be made to main or v12.0; if I should switch it to v0.12 (to be used with milli) please let me know.

2023-01-04 13:40 UTC, Kerollmops requested changes
> You could investigate using POSIX semaphores within milli/meilisearch as well for the possible speed improvements they bring, but that is outside the scope of this PR.

[This comment from Howard](https://github.com/meilisearch/heed/issues/135#issuecomment-1310643995) can be very interesting! Using POSIX semaphores can bring new issues. 

> Also not sure whether this PR should be made to main or v0.12; if I should switch it to v0.12 (to be used with milli) please let me know.

Yes, you must start from the branch meilisearch and milli uses which is v0.12.

2023-01-04 17:24 UTC, GregoryConrad commented
> [This comment from Howard](https://github.com/meilisearch/heed/issues/135#issuecomment-1310643995) can be very interesting! Using POSIX semaphores can bring new issues. There are information about the C defines that we can use with LMDB [in the Makefile](https://github.com/LMDB/lmdb/blob/3947014aed7ffe39a79991fa7fb5b234da47ad1a/libraries/liblmdb/Makefile#L6-L19) (more in the mdb.c).

Very true. I will note that if building meili into a Docker image, however, I would imagine that it would make sense to use POSIX semaphores even with that drawback (specifically, not cleaning up on a crash) since the container would just be restarted and the semaphore(s) would consequently be closed as soon as the container exits. However, if building meili into just an executable, and not in a container, it would still make sense to use SysV semaphores (at least not on iOS/macOS). All just depends on the target platform/use case.

> Yes, you must start from the branch meilisearch and milli uses which is v0.12.

Noted; will switch this PR over to `v0.12` if I can. Otherwise, I will open a new PR.

2023-01-04 17:30 UTC, GregoryConrad commented on heed/Cargo.toml
> +posix-sem = ["lmdb-rkv-sys/posix-sem"]
Looks like I am going to have to recreate the PR because changing the base didn't work as I wanted. Will update the docs in the new PR.

2023-01-04 17:47 UTC, closed without merging