Fix #163: Apprend examples fixed and documentation.
meilisearch/heed pull request #181
Opened 2023-07-11 12:59 UTC by darnuria

Now documentation of KeyExist Error describe the case of append with unordered data.

Also change the examples to use the append function.

## Related issue
Fixes #163

## What does this PR do?
- ...

## PR checklist

Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

2023-07-11 15:33 UTC, Kerollmops requested changes

2023-07-11 15:33 UTC, Kerollmops commented on heed/src/mdb/lmdb_error.rs
> +    /// that don't respect the database ordering.
```suggestion
    /// May also be returned by the `append` iterator methods when the appended key
    /// doesn't respect the database ordering.
```

2023-07-11 22:00 UTC, Kerollmops commented
Thank you very much ❤️

2023-07-11 22:00 UTC, merged

2023-07-12 09:13 UTC, darnuria commented
Thanks for the review and your time!